#ifndef _STRINGRESOURCE_
#define _STRINGRESOURCE_

#define STRINGBASE 100
#define IDS_MUSTBE_METHOD STRINGBASE + 1
#define IDS_FAIL_METHOD STRINGBASE + 2
#define IDS_INTERNAL_ERROR STRINGBASE + 3
#define IDS_OUT_OF_RESOURCES STRINGBASE + 4
#define IDS_ERROR STRINGBASE + 5
#define IDS_NOT_IMPLEMENTED STRINGBASE + 6
#define IDS_FAIL_EXECUTE STRINGBASE + 7
#define IDS_IMPROPER_NUMBER_OF_ARGUMENTS STRINGBASE + 8
#define IDS_OBJECT_NOT_ITERABLE STRINGBASE + 9
#define IDS_UNABLE_TO_DEREFERENCE STRINGBASE + 10
#define IDS_INVALID_ARGUMENT STRINGBASE + 11
#define IDS_ILLEGAL_METHOD_CALL STRINGBASE + 12
#define IDS_NUMERIC_LOSS_OF_PRECISION STRINGBASE + 13
#define IDS_NON_INDEXED_ITERATOR_RETURN STRINGBASE + 14
#define IDS_UNABLE_TO_READ_MEMORY STRINGBASE + 15
#define IDS_OBJECT_HAS_NO_LOCATION STRINGBASE + 16
#define IDS_OBJECT_HAS_NO_SIZE STRINGBASE + 17
#define IDS_USER_ABORT STRINGBASE + 18
#define IDS_CANNOT_WRITE STRINGBASE + 19
#define IDS_LOCATION_IS_NOT_ADDRESS STRINGBASE + 20
#define IDS_ILLEGAL_CUSTOM_MARSHALING STRINGBASE + 21
#define IDS_CANNOT_MODIFY_OBJECT_MODEL STRINGBASE + 22
#define IDS_METADATA_KEY_NOT_FOUND STRINGBASE + 23
#define IDS_PARTIAL_MEMORY_READ STRINGBASE + 24
#define IDS_UNABLE_TO_WRITE_MEMORY STRINGBASE + 25
#define IDS_PARTIAL_MEMORY_WRITE STRINGBASE + 26
#define IDS_CANNOT_CREATE_EXTENDO STRINGBASE + 27

#endif // _STRINGRESOURCE_
