
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'
  major: 1
  minor: 1
  majorDotMinor: '$(major).$(minor)'
  revision: $[counter(variables['majorDotMinor'], 0)]

steps:
- template: Build-Steps.yml
  parameters:
    BuildConfiguration: $(buildConfiguration)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: bin'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\Exdi\exdigdbsrv\$(buildConfiguration)'

- task: PublishSymbols@2
  displayName: 'Source index symbols 2'
  inputs:
    SearchPattern: '$(Build.SourcesDirectory)\Exdi\exdigdbsrv\$(buildConfiguration)\**\*.pdb'
    SymbolServerType: 'TeamServices'

- task: ms-vscs-artifact.build-tasks.artifactSymbolTask-1.artifactSymbolTask@0
  displayName: 'Publish to Symbols to Artifact Services'
  inputs:
    symbolServiceURI: 'https://microsoft.artifacts.visualstudio.com/DefaultCollection'
    requestName: 'DebuggingExperiences/$(Build.BuildNumber)/$(Build.BuildId)'
    sourcePath: '$(Build.SourcesDirectory)\Exdi\exdigdbsrv'
    expirationInDays: '365'

#Add the ExdiGdbSrv vpack steps.

- task: CmdLine@2
  displayName: dir files for debugging
  inputs:
    script: >
      echo dir Build.SourcesDirectory...

      dir /s/b $(Build.SourcesDirectory)\Exdi\exdigdbsrv

      echo dir Exdi\exdigdbsrv\Release\x64...

      dir $(Build.SourcesDirectory)\Exdi\exdigdbsrv\Release\x64

      echo dir Exdi\exdigdbsrv\Release\ARM64...

      dir $(Build.SourcesDirectory)\Exdi\exdigdbsrv\Release\ARM64

      md $(Agent.TempDirectory)

      md $(Agent.TempDirectory)\ExdiGdbSrv.vpack.temp

      md $(Agent.TempDirectory)\ExdiGdbSrv.vpack.temp\x64

      md $(Agent.TempDirectory)\ExdiGdbSrv.vpack.temp\ARM64

      echo Copy files ...

      copy $(Build.SourcesDirectory)\Exdi\exdigdbsrv\Release\x64\ExdiGdbSrv.dll $(Agent.TempDirectory)\ExdiGdbSrv.vpack.temp\x64
      
      copy $(Build.SourcesDirectory)\Exdi\exdigdbsrv\GdbSrvControllerLib\systemregisters.xml $(Agent.TempDirectory)\ExdiGdbSrv.vpack.temp\x64

      copy $(Build.SourcesDirectory)\Exdi\exdigdbsrvGdbSrvControllerLib\exdiConfigData.xml $(Agent.TempDirectory)\ExdiGdbSrv.vpack.temp\x64

      copy $(Build.SourcesDirectory)\Exdi\exdigdbsrv\Release\ARM64\ExdiGdbSrv.dll $(Agent.TempDirectory)\ExdiGdbSrv.vpack.temp\ARM64

      copy $(Build.SourcesDirectory)\Exdi\exdigdbsrv\GdbSrvControllerLib\systemregisters.xml $(Agent.TempDirectory)\ExdiGdbSrv.vpack.temp\ARM64

      copy $(Build.SourcesDirectory)\Exdi\exdigdbsrvGdbSrvControllerLib\exdiConfigData.xml $(Agent.TempDirectory)\ExdiGdbSrv.vpack.temp\ARM64

- task: PkgESVPack@12
  displayName: 'Create ExdiGdbSrv VPack '
  inputs:
    sourceDirectory: '$(Agent.TempDirectory)\ExdiGdbSrv.vpack.temp'
    description: 'ExdiGdbSrv binary'
    pushPkgName: ExdiGdbSrv.vpack.binary
