//----------------------------------------------------------------------------
//
// ExdiGdbSrv.idl
//
// Copyright (c) Microsoft. All rights reserved.
//
//----------------------------------------------------------------------------

import "oaidl.idl";
import "ocidl.idl";
#include "exdi3.idl"

//Used for internal synchronization
[object, oleautomation, uuid(6b76dcda-ece4-400b-ac9d-af17d71bca50)]
interface IAsynchronousCommandNotificationReceiver : IUnknown
{
    HRESULT OnAsynchronousCommandCompleted();
    HRESULT PerformKeepaliveChecks();
}

[
uuid(72d4aeda-9723-4972-b89a-679ac79810ef),
version(1.0)
]

library ExdiGdbSrvLib
{
	importlib("stdole2.tlb");
	[
		uuid(29f9906e-9dbe-4d4b-b0fb-6acf7fb6d014)		
	]
	coclass LiveExdiGdbSrvServer
	{
		[default] interface IeXdiServer3;
        interface IeXdiARM4Context3;
        interface IeXdiX86_64Context3;
        interface IeXdiX86ExContext3;
        interface IeXdiArmV8Arch64Context3;
        interface IAsynchronousCommandNotificationReceiver;
        interface IeXdiControlComponentFunctions;
	};
};

import "shobjidl.idl";
